# Generated by Django 4.1.2 on 2022-10-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(choices=[('eng', 'English'), ('fr', 'French'), ('ger', 'German'), ('sp', 'Spanish')], default='eng', help_text='Availble languages', max_length=20),
        ),
    ]
