# Generated by Django 4.1.2 on 2022-10-25 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_bookinstance_imprint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='dat_of_death',
            new_name='date_of_death',
        ),
    ]
