# Generated by Django 4.1.2 on 2022-10-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_rename_dat_of_death_author_date_of_death'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('French', 'French'), ('German', 'German'), ('Spanish', 'Spanish')], default='English', help_text='Availble languages', max_length=20),
        ),
    ]
