# Generated by Django 4.1.2 on 2022-10-27 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_language_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='summery',
            new_name='summary',
        ),
    ]
