# Generated by Django 4.1.2 on 2022-10-31 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'set book as returned'),)},
        ),
    ]
